### ISSUE TITLE
VC test instance seems to be down

### ISSUE THREAD

**Issue by Dimitrispant** [up2university/knockplop#12]
@misi When I tried to create a room on the test instance I saw this error:

![image](https://user-images.githubusercontent.com/13375110/55306990-c1682e00-545e-11e9-8b64-bbb893be5e27.png)

**Comment by misi** [comment]
Something happened in the docker container.

**Comment by misi** [comment]
@michzimny can you please check the docker container logs and restart it?

**Comment by michzimny** [comment]
We have lost the VM. It's available now.
