### ISSUE TITLE
Hide functions that are not ready

### ISSUE THREAD

**Issue by michzimny** [up2university/knockplop#2]
Could hide functions (e.g. buttons) that are not ready. 

For instance: settings button or phone ending buttom (seems to not working).

**Comment by misi** [comment]
Phone Ending works.
The settings could be make hidden for sure.

**Comment by michzimny** [comment]
Ok, ending works (cannot reproduce my earlier problems).

**Comment by misi** [comment]
I have commented out in this commit the "settings button":
https://github.com/up2university/knockplop/commit/2eca7fa6a4ade1ac6a471732a480c72cfe689227
Please try it...

**Comment by michzimny** [comment]
Automatically deployed, see #4 .
