### ISSUE TITLE
Moodle integration

### ISSUE THREAD

**Issue by andreacorleto** [up2university/knockplop#3]
Not working properly. Web page for call displayed not in the right way. No video/audio

**Comment by misi** [comment]
Could you give me more details?
e.g. browser, version etc...

**Comment by andreacorleto** [comment]
Both on Chrome and Firefox
Chrome version: 64.0.3282.140 
Firefox Quantum: 58.0.1

**Comment by misi** [comment]
Thx.
Could you help me more to reproduce the issue? Thanks in advance..
I tried from chrome: 64.0.3282.140/FireFox 58.0.1 https://vc.test.up2university.eu/bbb

And it seems working for me..

**Comment by misi** [comment]
Could you share the browser js/dev console output

**Comment by andreacorleto** [comment]
This is the link to the page coming from Moodle: https://vc.test.up2university.eu//OTNhNmEz

Firefox
SyntaxError: expected expression, got '<'  client-config.js:1
TypeError: asm.js type error: initializer of exported object literal must be name of function  webtorrent.min.js:1:197424
SyntaxError: expected expression, got '<'  app.js:1
ReferenceError: pageReady is not defined  OTNhNmEz:140:9

Chrome
client-config.js:1 Uncaught SyntaxError: Unexpected token <
webtorrent.min.js:1 Invalid asm.js: Expected function name
app.js:1 Uncaught SyntaxError: Unexpected token <
OTNhNmEz:140 Uncaught ReferenceError: pageReady is not defined
    at OTNhNmEz:140

**Comment by misi** [comment]
@michzimny  made some changes and a new build. 
I think you made your test during that time.
Could you repeat it now again. Thanks..

**Comment by misi** [comment]
@michzimny @andreacorleto 

I think I see the issue. There is a double "//" in URI. It is a Moodle config error.
[https://vc.test.up2university.eu//OTNhNmEz](https://vc.test.up2university.eu//OTNhNmEz)
Please correct in moodle the base uri and remove the final "/" if possible

**Comment by michzimny** [comment]
I just fixed up Moodle config.

**Comment by andreacorleto** [comment]
ok, now it seems to be working. I'll give some test in the next days.
