### ISSUE TITLE
Branching and CI

### ISSUE THREAD

**Issue by michzimny** [up2university/knockplop#4]
May I set "up2u" as the main branch in this repostory?

I would also quickly set up Continuous Integration to automatically deploy any changes in this branch to https://vc.test.up2university.eu/ 

Any comments, objections? :)

**Comment by misi** [comment]
No objections..

In longer term I want to make knockplop more customizable and put only design customization only in the branch.. 
So converge back to knockplop.

**Comment by michzimny** [comment]
Done. 10-20 minutes (building takes a lot of time) after every commit to branch up2u, the new version gets deployed to https://vc.test.up2university.eu/
