### ISSUE TITLE
Unable to see other participants

### ISSUE THREAD

**Issue by michzimny** [up2university/knockplop#5]
The screenshots (taken during the same call from the two computers) present what happens to me very often after joining a call (Win10, latest Firefox).

![knockplop1](https://user-images.githubusercontent.com/1483196/36315896-20b5db04-1339-11e8-9931-07d5452e7562.png)
![knockplop2](https://user-images.githubusercontent.com/1483196/36315898-20d18188-1339-11e8-8d35-3b2a0cb7ab43.png)

**Comment by michzimny** [comment]
@misi, have you experienced such issue? What could we done about this?

**Comment by misi** [comment]
I will check it asap.. Sorry for delay..
No I didn't saw such issues and may I need help to reproduce it. 
Thanks for your patience...

**Comment by misi** [comment]
@michzimny could you try in the mean time replace in server.js in rest uri the transport and add udp too.
instead of "transport=tcp" use "transport=udp%2Ctcp"

**Comment by misi** [comment]
I have started work on it. 
According you experience have the change above caused any change in behaviour?

**Comment by misi** [comment]
For me it seems working from public network.
Could you send your logs from a new tab "about:webrtc"

Thanks..
![kep](https://user-images.githubusercontent.com/311629/36715651-6e7b58a8-1b97-11e8-99a1-c26f0588c070.png)

**Comment by misi** [comment]
@michzimny I run up2u branch on https://lutra.lab.vvc.niif.hu:8443/ and I don't experience any issue using it. 

Please check it if you could reproduce these issues on top of it.

Thanks!

**Comment by misi** [comment]
@michzimny  could You please also try to `npm update` the dependencies too..

**Comment by misi** [comment]
Could you reproduce the issues on  https://lutra.lab.vvc.niif.hu:8443 too?

**Comment by michzimny** [comment]
> Could you reproduce the issues on https://lutra.lab.vvc.niif.hu:8443 too?

Here it works properly.

I use latest Firefox.

At vc.test.up2university.eu it currently doesn't even ask for camera permissions. Page about:webrtc is empty (sections "Session Statistics" and "Connection Log" are empty). JS console: https://pastebin.com/34y4UW6M

> @michzimny could you try in the mean time replace in server.js in rest uri the transport and add udp too.
> instead of "transport=tcp" use "transport=udp%2Ctcp"

After that, my browser started to ask for permissions. However, the result was still the same, i.e. on both machines I don't see the other person. But then, I just refreshed the pages on both machines and it started to work properly. I cannot reproduce the original problem.

I haven't tried `npm update` so far.
