### ISSUE TITLE
Chrome keeps seeing my screen after I stopped sharing

### ISSUE THREAD

**Issue by michzimny** [up2university/knockplop#6]
I connect latest Firefox with latest Chrome without the screen sharing plugin. I start screen sharing from Firefox. The Chrome user cannot see Firefox' screen (just an empty box). When Firefox user stops screen sharing, then Chrome now starts to present Firefox' screen! And the Firefox user is not aware that the others see his/her screen...

The same happens at https://lutra.lab.vvc.niif.hu:8443/asdf

I've been able to reproduce it all the time.

When the Chrome user refreshes the page during the expected screen sharing, then it works fine - the shared screen can be seen. However, when now Firefox stops sharing, Chrome sees empty box for that participant. It is fine again if Chrome reloads the page.

**Comment by misi** [comment]
I hope I fixed it.
I have made some changes to move from old spec behavior to new spec behavior so moved away from "add/removeStream + Offer/Answer"  to  "replaceTrack without renegotiation". 
According my tests it works between the actual chrome and Firefox..

@michzimny  please try it, and let me know your experiences!

**Comment by misi** [comment]
Sorry, it was not fully fixed. 
I hope it is now. (at least works for me).
I just recently pushed the commit so please wait out the timeout and after retest it.

**Comment by michzimny** [comment]
Now I cannot reproduce. So it seems to be fine. Thanks.
